-- schema/01_create_users.sql
DROP TABLE IF EXISTS pomodoros CASCADE;
-- CREATE POMODOROS
CREATE TABLE pomodoros ( 
  id SERIAL PRIMARY KEY NOT NULL, 
  start_time TIMESTAMP WITH TIME ZONE NOT NULL, 
  end_time TIMESTAMP WITH TIME ZONE NOT NULL, 
  duration INTERVAL NOT NULL, 
  task_id INTEGER NOT NULL REFERENCES tasks (id) ON DELETE CASCADE, 
  user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE 
);