-- schema/03_pomodoros.sql
DROP TABLE IF EXISTS pomodoros CASCADE;
-- CREATE POMODOROS
CREATE TABLE pomodoros ( 
  id SERIAL PRIMARY KEY NOT NULL,    
  focus_time INTERVAL NOT NULL, 
  break_time INTERVAL NOT NULL, 
  repeat INTEGER NOT NULL, 
  start_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  estimated_end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE,   
  task_id INTEGER REFERENCES tasks (id) ON DELETE CASCADE, 
  user_id INTEGER REFERENCES users (id) ON DELETE CASCADE 
);